# -*- coding: utf-8 -*-
"""Analysis_11/07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTZpPmG9JKnlu8TBcs7D4ovvh5wDuwZm
"""

# Import essential packages
import pandas as pd
import numpy as np
import matplotlib as plt
import plotly as py

# Import data from Github
eco_status_url = 'https://raw.githubusercontent.com/Kittisak-M/Bridging-the-Gap-Enhancing-Life-Quality-in-Thailand/main/data_set/Life%20Expectancy%20Data.csv'

main_data = 'https://raw.githubusercontent.com/Kittisak-M/Bridging-the-Gap-Enhancing-Life-Quality-in-Thailand/main/data_set/Data.csv'

# Read csv files
eco_status = pd.read_csv(eco_status_url)

data = pd.read_csv(main_data, encoding='latin-1')

eco_status

# Drop duplicate
ct_status = eco_status[['Country', 'Status']].drop_duplicates().reindex()

# Change economics status to float
ct_status['Status'] = ct_status['Status'].replace('Developing',0)
ct_status['Status'] = ct_status['Status'].replace('Developed',1)

# Check the change
ct_status['Status'].unique()

# Count developed and developing countries
ct_status['Status'].value_counts()

"""# DATA"""

eco_status.head(5)

# Drop null value in
data.dropna(subset=['Series Name'], inplace=True)

# Reshape dataframe
melted_data = data.melt(id_vars=['Series Name', 'Country Name', 'Country Code'],
                    var_name='Year',
                    value_name='Value')

# Extract the year from the column names
melted_data['Year'] = melted_data['Year'].str.extract('(\d{4})').astype(int)

melted_data['Series Name'].unique()

melted_data.isnull().sum()

# Remove unnecessary rows
melted_data = melted_data.dropna(subset=['Country Name'])



# Ensure all column names are strings
melted_data.columns = melted_data.columns.astype(str)

# Replace spaces with underscores in column names
melted_data.columns = melted_data.columns.str.replace(' ', '_')

# Lower text in column header
melted_data.columns = melted_data.columns.str.lower()

melted_data

ct_status

# Lower columns header
ct_status.columns = ct_status.columns.str.lower()

# Change col

# Join to get economy status
cleansed_data = pd.merge(melted_data,ct_status, how='left',on='country_name')

cleansed_data



